"""make employee_id CASCADE on delete in status_history

Revision ID: 25cd2ef418e1
Revises: 10acbc6f9698
Create Date: 2025-12-17 03:49:22.037573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cd2ef418e1'
down_revision: Union[str, Sequence[str], None] = '10acbc6f9698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('status_history_employee_id_fkey'), 'status_history', type_='foreignkey')
    op.create_foreign_key(None, 'status_history', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status_history', type_='foreignkey')
    op.create_foreign_key(op.f('status_history_employee_id_fkey'), 'status_history', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
