"""make leader_employee_id CASCADE on delete in teams

Revision ID: 10acbc6f9698
Revises: 8f4b6e3c1d2a
Create Date: 2025-12-17 01:24:23.433026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10acbc6f9698'
down_revision: Union[str, Sequence[str], None] = '8f4b6e3c1d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teams_leader_employee_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'employees', ['leader_employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_leader_employee_id_fkey'), 'teams', 'employees', ['leader_employee_id'], ['id'])
    # ### end Alembic commands ###
