"""add email to employees

Revision ID: 2e93d87a3aa9
Revises: 5553cd52829d
Create Date: 2025-11-06 02:50:22.673580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93d87a3aa9'
down_revision: Union[str, Sequence[str], None] = '5553cd52829d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'employees',
        sa.Column('email', sa.String(), nullable=False, server_default='unknown@example.com')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
