"""edit employees

Revision ID: 14afeb5dd725
Revises: 2e93d87a3aa9
Create Date: 2025-11-10 21:27:57.664301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14afeb5dd725'
down_revision: Union[str, Sequence[str], None] = '2e93d87a3aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('tg', sa.String(), nullable=True))
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'unknown@example.com'::character varying"))
    op.alter_column('employees', 'city',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    )
    op.alter_column('employees', 'phone',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    )
    op.alter_column('employees', 'mattermost',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'unknown@example.com'::character varying"))
    op.drop_column('employees', 'tg')
    op.alter_column('employees', 'city',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    )
    op.alter_column('employees', 'phone',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    )
    op.alter_column('employees', 'mattermost',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    )
    # ### end Alembic commands ###
