"""add password_changed_at_ts in users

Revision ID: 7373f8167d4a
Revises: d280d9a2dd22
Create Date: 2025-11-30 21:23:26.334533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7373f8167d4a'
down_revision: Union[str, Sequence[str], None] = 'd280d9a2dd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_changed_at_ts', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at_ts')
    # ### end Alembic commands ###
